def sout = new StringBuilder(), serr = new StringBuilder()
def proc = 'ls /var/lib/jenkins/workspace/Package_Application/java-tomcat-sample/target'.execute()


pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('view artifact loc'){
            steps{
                    proc.consumeProcessOutput(sout, serr)
                    proc.waitForOrKill(1000)
                    println "out> $sout\nerr> $serr"
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_Application_Staging_Env'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
    }
}